# Generated by Django 4.0.5 on 2022-06-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_No', models.IntegerField()),
                ('class_Name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_No', models.IntegerField()),
                ('stu_Name', models.CharField(max_length=64)),
                ('stu_Class', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_No', models.IntegerField()),
                ('teacher_Name', models.CharField(max_length=64)),
                ('teacher_Class', models.CharField(max_length=64)),
            ],
        ),
    ]
