# Generated by Django 4.0.5 on 2022-06-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_No',
        ),
        migrations.AddField(
            model_name='class',
            name='class_stu_No',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_tea_No',
            field=models.ManyToManyField(to='app1.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stu_No',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_No',
            field=models.PositiveIntegerField(),
        ),
    ]
