# Generated by Django 4.0.5 on 2022-06-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_class_class_no_class_class_stu_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_stu_No',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_tea_No',
        ),
    ]
