# Generated by Django 4.0.5 on 2022-06-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_class_class_stu_no_remove_class_class_tea_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_No',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_No',
        ),
    ]
