# Generated by Django 4.0.5 on 2022-06-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_student_stu_no_remove_teacher_teacher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_Class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.class'),
        ),
    ]
