# Generated by Django 4.0.5 on 2022-06-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_student_stu_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_Class',
            new_name='student_Class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='stu_Name',
            new_name='student_Name',
        ),
    ]
