# Generated by Django 4.0.5 on 2022-06-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_stu_class_student_student_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_Class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_Class',
            field=models.ManyToManyField(to='app1.class'),
        ),
    ]
